PROCESS_FEED = 'process_feed'
PARSE_VACANCY = 'parse_vacancy'
EXTRACT_VACANCY = 'extract_vacancy'
LEXICON_EXPAND = 'lexicon_expand'
LEXICON_EMBED = 'lexicon_embed'
ENQUEUE_VACANCIES = 'enqueue_vacancies'
